# Generated by Django 4.2 on 2025-01-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_comment_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="posted_by",
            field=models.CharField(default="avirat", max_length=100),
            preserve_default=False,
        ),
    ]
